---
# Name your file secrets.yml
development:
  # Infrastructure
  DB_FILENAME: db/local/dev.db
  ACCESS_TOKEN: <your_token_here>
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <your_secret_here>

test:
  # Infrastructure
  DB_FILENAME: db/local/test.db
  ACCESS_TOKEN: <your_token_here>
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <your_secret_here>

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  ACCESS_TOKEN: <your_token_here>
  # Application
  APP_HOST: <link_to_the_live_app>
  SESSION_SECRET: <your_secret_here>